dist: trusty
sudo: required
services:
    - docker
cache:
  directories:
    - $HOME/gopath/pkg
    - /var/lib/docker

language: go

os:
  - linux

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master
matrix:
    fast_finish: true
    allow_failures:
        - go: master

install:
    - ./travis/install.sh

script:
    - ./travis/test.sh
